apiVersion: v1
kind: ConfigMap
metadata:
  name: posfiap-config
  namespace: posfiap
  labels:
    app.kubernetes.io/name: posfiap
    app.kubernetes.io/component: config
data:
  DB_HOST: "fiap-officine-homolog-rds.chmmasky8j6y.sa-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  APP_ENV: "production"
  APP_DEBUG: "false"
  AUTH_LAMBDA_URL: "https://kai652jumh.execute-api.sa-east-1.amazonaws.com"
  UV_NO_SYNC: "1"
