apiVersion: v1
kind: Secret
metadata:
  name: posfiap-secrets
  namespace: posfiap
  labels:
    app.kubernetes.io/name: posfiap
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  DB_USER: "dbadmin"
  DB_PASSWORD: "FiapOfficine2026Homolog!"
  DB_NAME: "officine_db"
  POSTGRES_USER: "dbadmin"
  POSTGRES_PASSWORD: "FiapOfficine2026Homolog!"
  POSTGRES_DB: "officine_db"
  JWT_SECRET_KEY: "fiap-officine-super-secret-jwt-key-2026-homolog"
  WEBHOOK_SHARED_SECRET: "fiap-webhook-secret-123"
