apiVersion: v1
kind: Secret
metadata:
  name: posfiap-secrets
  namespace: posfiap
  labels:
    app.kubernetes.io/name: posfiap
    app.kubernetes.io/component: secrets
type: Opaque
data:
  DB_USER: <base64-encoded-db-user>
  DB_PASSWORD: <base64-encoded-db-password>
  DB_NAME: <base64-encoded-db-name>
  POSTGRES_USER: <base64-encoded-postgres-user>
  POSTGRES_PASSWORD: <base64-encoded-postgres-password>
  POSTGRES_DB: <base64-encoded-postgres-db>
  JWT_SECRET_KEY: <base64-encoded-jwt-secret>
  WEBHOOK_SHARED_SECRET: <base64-encoded-webhook-shared-secret>
